FROM python:3.9
WORKDIR /geocode

COPY requirements.txt /geocode/requirements.txt

RUN apt-get -qq update && apt-get -qq install -y \
    curl \
    git \
    wget \
    libproj-dev \
    proj-data \
    proj-bin \
    libgeos-dev \
    libgdal-dev \
    python-gdal \
    gdal-bin \
    > /dev/null

RUN pip install --no-cache-dir -r /geocode/requirements.txt > /dev/null

COPY . /geocode/

#python -m unittest Tests.test_geocode
CMD ["python", "-m", "unittest", "Tests.test_geocode"]
